apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diabetes
  template:
    metadata:
      labels:
        app: diabetes
    spec:
      containers:
        - name: diabetes
          image: diabetes-app:latest
          ports:
            - containerPort: 8501
          env:
            - name: GEMINI_API_KEY
              value: "Your-Gemini-API-token"
---
apiVersion: v1
kind: Service
metadata:
  name: diabetes-service
spec:
  type: NodePort
  selector:
    app: diabetes
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30031

